apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 377755048459.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 377755048459.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ca4b20cf
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
